# Generated by Django 3.0.3 on 2020-04-19 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200418_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 19)),
        ),
    ]
